default_context:
  project_name: 'fasthomeapi'
  project_slug: 'fasthomeapi'
  domain_main: 'fasthomeapi.com'
  domain_staging: 'stag.fasthomeapi.com'
  docker_swarm_stack_name_main: 'fasthomeapi-com'
  docker_swarm_stack_name_staging: 'stag-fasthomeapi-com'
  secret_key: 'f1834fa9da95af3e79e2e868765db24b76cdd50ee28762fcfbea2e877160832b'
  first_superuser: 'brian'
  first_superuser_password: 'Bmm803Emc'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.fasthomeapi.com, https://stag.fasthomeapi.com, https://fasthomeapi.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: 'mail.brianmask.com'
  smtp_user: 'brian'
  smtp_password: 'Bmm803Emc'
  smtp_emails_from_email: 'brian@brianmask.com'
  postgres_password: 'Bmm803Emc'
  pgadmin_default_user: 'brian'
  pgadmin_default_user_password: 'Bmm803Emc'
  traefik_constraint_tag: 'fasthomeapi.com'
  traefik_constraint_tag_staging: 'stag.fasthomeapi.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Bmm803Emc'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
